name: chat_life
description: A new Flutter project.
publish_to: "none"

version: 0.0.3+4

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  another_flushbar: ^1.12.30
  based_avatar: ^1.0.3
  based_list: ^1.1.2
  based_split_view: ^1.0.0
  dart_date: ^1.3.2
  dynamic_color: ^1.6.8
  file_picker: ^6.1.1
  flutter_chat_ui: ^1.6.10
  flutter_chat_types: ^3.6.2
  flutter_displaymode: ^0.6.0
  flutter_link_previewer: ^3.2.2
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  based_qr: ^1.0.0
  system_tray: ^2.0.3
  url_launcher: ^6.2.1
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Torus
      fonts:
        - asset: assets/fonts/Torus-Thin.otf
          weight: 100
        - asset: assets/fonts/Torus-Light.otf
          weight: 300
        - asset: assets/fonts/Torus-Regular.otf
          weight: 400
        - asset: assets/fonts/Torus-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Torus-Bold.otf
          weight: 700
        - asset: assets/fonts/Torus-Heavy.otf
          weight: 900
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
