name: chat_life
description: A new Flutter project.
publish_to: "none"

version: 0.0.3+4

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  based_avatar: ^1.0.4
  based_list: ^1.1.3
  based_qr: ^1.0.0
  based_splash_page: ^1.0.1
  based_split_view: ^1.0.5
  dart_date: ^1.3.2
  dio: ^5.3.3
  dynamic_color: ^1.6.8
  file_picker: ^6.1.1
  flutter_displaymode: ^0.6.0
  flutter_link_previewer: ^3.2.2
  flutter_quill: ^8.6.1
  flutter_riverpod: ^2.4.8
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  material_color_utilities: ^0.5.0
  open_filex: ^4.3.4
  path_provider: ^2.1.1
  package_info_plus: ^4.2.0
  riverpod_annotation: ^2.3.2
  shared_preferences: ^2.2.2
  system_tray: ^2.0.3
  url_launcher: ^6.2.1
  window_manager: ^0.3.7
  web_socket_channel: ^2.4.0

  models:
    path: ../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.7
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Torus
      fonts:
        - asset: assets/fonts/Torus/Torus-Thin.otf
          weight: 100
        - asset: assets/fonts/Torus/Torus-Light.otf
          weight: 300
        - asset: assets/fonts/Torus/Torus-Regular.otf
          weight: 400
        - asset: assets/fonts/Torus/Torus-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Torus/Torus-Bold.otf
          weight: 700
        - asset: assets/fonts/Torus/Torus-Heavy.otf
          weight: 900
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans/MiSans-Regular.ttf
    - family: CascadiaCodePL
      fonts:
        - asset: assets/fonts/CascadiaCodePL/CascadiaCodePL-Regular.otf
