name: models
description: Define models used in app & server.
version: 2023.11.22

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dart_jsonwebtoken: ^2.12.1
  freezed_annotation: ^2.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  test: ^1.24.0
  very_good_analysis: ^5.1.0
